#The integer value (1-6) assigned to ColorScheme determines the color scheme of the /cstaff message like so:
#1 = DARK_AQUA/BLUE (default), 2 = DARK_GREEN/GREEN, 3 = BLACK/DARK_GRAY (boring), 4 = DARK_RED/RED, 5 = DARK_PURPLE/LIGHT_PURPLE, 6 = GOLD/YELLOW
ColorScheme: 1